/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package favoritesites;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Acer
 */
public class SharedVisits extends javax.swing.JFrame {

     Connection con;
     PreparedStatement ps;
     ResultSet rs;
     
     
     private String loggedInUsername; // in order to carry username to other classes
    
    public void setLoggedInUsername(String username) {
        loggedInUsername = username;
    }
    
     public void startLoadingTable() {
    if (loggedInUsername != null) {
        loadTable();
        }
    }
    /**
     * Creates new form SharedVisits
     */
    public SharedVisits() {
        initComponents();
        loadTable();
}
 private void loadTable() {
        try {
        // Establish database connection
        con = DriverManager.getConnection("jdbc:mysql://localhost/favorite_sites","root","10293847");
        }catch (SQLException ex) {
            Logger.getLogger(SharedVisits.class.getName()).log(Level.SEVERE, null, ex);
        }


        String sharedVisitsQuery = "SELECT username_from, visit_id FROM sharedvisits WHERE username_to = ?";
        
         try {
          PreparedStatement sharedVisitsPs = con.prepareStatement(sharedVisitsQuery);
          sharedVisitsPs.setString(1, loggedInUsername); 
          ResultSet sharedVisitsRs = sharedVisitsPs.executeQuery();
            
           
    
            DefaultTableModel model = (DefaultTableModel)sharedTable.getModel();
            TableRowSorter rowSorter = new TableRowSorter(model);         
            sharedTable.setRowSorter(rowSorter);
            
            while(sharedVisitsRs.next()){
            String usernameFrom = sharedVisitsRs.getString("username_from");
            String visitInfoQuery = "SELECT visit_id, country_name, city_name, season_visited, best_feature FROM visits WHERE visit_id = ?";
            PreparedStatement visitInfoPs = con.prepareStatement(visitInfoQuery);
            visitInfoPs.setInt(1, sharedVisitsRs.getInt("visit_id"));
            ResultSet visitInfoRs = visitInfoPs.executeQuery();
            while (visitInfoRs.next()) {
                    model.addRow(new String[]{ 
                    usernameFrom,
                    visitInfoRs.getString("visit_id"),
                    visitInfoRs.getString("country_name"),
                    visitInfoRs.getString("city_name"),                    
                    visitInfoRs.getString("season_visited"),
                    visitInfoRs.getString("best_feature")
                });
            }
        }
        
         
                    
        } catch (SQLException ex) {
            Logger.getLogger(SharedVisits.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sharedTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sharedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username From", "Visit ID", "Country", "City", "Season Visited", "Best Feature"
            }
        ));
        jScrollPane1.setViewportView(sharedTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SharedVisits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SharedVisits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SharedVisits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SharedVisits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SharedVisits().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sharedTable;
    // End of variables declaration//GEN-END:variables
}
